gzip_assets: off
compress_assets: off
package_assets: off

javascripts:
  library:
    - public/javascripts/frameworks/jquery/jquery.js
    - public/javascripts/frameworks/jquery/jquery-ui.js
    - public/javascripts/frameworks/jquery/jrails.js
    - public/javascripts/frameworks/jquery/extensions/*.js
    - public/javascripts/frameworks/validatious/XMLHttpRequest.js
    - public/javascripts/frameworks/validatious/v2.standalone.full.min.js
    - public/javascripts/frameworks/validatious/v2.config.js
    - public/javascripts/frameworks/validatious/v2.rails.js
    - public/javascripts/frameworks/code-mirror/codemirror.js

  site:
    - public/javascripts/application.js
    - public/javascripts/site/*.js

stylesheets:
  site:
    - public/stylesheets/reset.css
    - public/stylesheets/application.css
